### ISSUE TITLE
How sensitive is microphone?

### ISSUE THREAD

**Issue by gwpl** [sparkfun/Sound_Detector#1]
I am looking for device capable for recognizing very delicate quite sounds. Are there any specs about properties of microphone used in given set?

**Comment by Jacquot-SFE** [comment]
The microphone element is the electret that we sell, the same as on our electret microphone breakout.

The datasheet for it is here:
http://cdn.sparkfun.com/datasheets/Sensors/Sound/CEM-C9745JAD462P2.54R.pdf
